name: Release
on:
  push:
    branches: ['release']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run build --if-present
        name: Build
      - run: npm run lint
        env:
          CI: true

  publish:
    if: github.ref == 'refs/heads/release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - name: Tests here
#        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
